# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Snapcast server
version: "0.4.5"
slug: snapcast-server
description: Snapcast server with Spotify connect and DLNA Renderer support
url: "https://github.com/DjFabFab/hassio-snapcast/tree/main/snapcast-server"
audio: true
host_network: true
ingress: true
ingress_port: 1780
panel_icon: "mdi:cast-audio"
privileged:
  - SYS_ADMIN
init: false
arch:
  # - armhf
  # - armv7
  - aarch64
  - amd64
  # - i386
map:
  - share:rw
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
  50000/tcp: 50000
  8200/tcp: 8200
ports_description:
  1704/tcp: Snapcast client connections
  1705/tcp: Snapcast's control interface
  1780/tcp: Snapcast websocket connections and web-interface
  8200/tcp: DLNA Discovery
  50000/tcp: DLNA Renderer
options:
  streams:
    streams: []
  buffer: 1000
  chunk_ms: 20
  codec: flac
  send_to_muted: false
  sampleformat: "44100:16:2"
  renderer_name: "Home Assistant DLNA Renderer"
  spotify_name: "Home Assistant Sound System"
  log_level: info
schema:
  # Use nested option to force yaml editor on addon's config page
  streams:
    streams: ["str"]
  buffer: int
  chunk_ms: int
  codec: list(pcm|flac|vorbis|opus)
  renderer_name: str
  send_to_muted: bool
  sampleformat: str
  spotify_name: str
  spotify_token: password?
  log_level: list(trace|debug|info|notice|warning|error|fatal)
image: "ghcr.io/djfabfab/{arch}-snapcast-server"
