# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
ARG BUILD_FROM=ghcr.io/hassio-addons/base:18.1.0
FROM $BUILD_FROM

ARG LIBRESPOT_VERSION=0.8.0
ARG GM_RENDER_RESURRECT_VERSION=v0.3

# Add Runtime Dependencies
RUN apk add --no-cache \
        dbus \
        nss \
        avahi-compat-libdns_sd \
        avahi \
        pulseaudio \
        alsa-plugins-pulse \
	    snapcast \
        alsa-utils \
        alsa-utils-doc \
        alsa-lib \
        alsaconf \
        alsa-ucm-conf \
        libupnp-dev \
        libnice-gstreamer \
        gst-plugins-base \
        gst-plugins-ugly \
        gst-plugins-good \
        gst-plugins-bad \
        gst-plugins-good-gtk \
        gst-libav \
        gstreamer-dev \
        gstreamer-tools

# See https://github.com/librespot-org/librespot/wiki/Compiling#addition-features for librespot compile features.
# Add Compiling Dependencies
RUN apk add --no-cache --virtual .build-dependencies \
        # cargo dependencies
        cargo \
        # cmake \
        avahi-dev
        # make \
        # rust-bindgen \
        # clang18-dev

RUN cargo install \
        --locked \
        --no-default-features \
        --features with-avahi,rustls-tls-native-roots \
        --root /usr \
        --bin librespot \
        --version ${LIBRESPOT_VERSION} \
        # --verbose \
        librespot

# Add Compiling Dependencies
RUN apk add --no-cache --virtual .build-dependencies \
        # gmrender-resurrect dependencies
        git \
        # build-base \
        # protobuf-dev \
        # pulseaudio-dev \
        autoconf \
        automake \
        # libtool \
        # pkgconf \  
        # gcc \
        g++ \
        make \
        cmake
        # rust-bindgen

RUN git clone https://github.com/hzeller/gmrender-resurrect.git \
	&& mkdir -p /gmrender-resurrect \
	&& cd /gmrender-resurrect \
        && git checkout ${GM_RENDER_RESURRECT_VERSION} \
	&& ./autogen.sh \
	&& ./configure \
	&& automake \
	&& make \
	&& make install

RUN apk del --no-cache --purge .build-dependencies \
	&& rm -fr \
                /tmp/* \
                ~/.cargo \
                /usr/.crates.toml \
                /usr/.crates2.json \
                /gmrender-resurrect

# RUN apk add --no-cache librespot=0.6.0-r0 --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing
RUN apk add --no-cache snapweb=0.9.2-r0 --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing

RUN addgroup root audio

RUN mkdir -p /var/run/dbus
        # && touch /var/run/dbus/system_bus_socket

# https://stackoverflow.com/a/75295879 dbus daemon slow start fix
RUN sed -i 's/ systemd//g' /etc/nsswitch.conf

# Copy root filesystem
COPY rootfs /

# Build arguments
ARG BUILD_ARCH
ARG BUILD_DATE
ARG BUILD_DESCRIPTION
ARG BUILD_NAME
ARG BUILD_REF
ARG BUILD_REPOSITORY
ARG BUILD_VERSION

# Labels
LABEL \
    io.hass.name="${BUILD_NAME}" \
    io.hass.description="${BUILD_DESCRIPTION}" \
    io.hass.arch="${BUILD_ARCH}" \
    io.hass.type="addon" \
    io.hass.version=${BUILD_VERSION} \
    maintainer="DjFabFab" \
    org.opencontainers.image.title="${BUILD_NAME}" \
    org.opencontainers.image.description="${BUILD_DESCRIPTION}" \
    org.opencontainers.image.vendor="DjFabFab's addons" \
    org.opencontainers.image.authors="DjFabFab" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.url="https://github.com/${BUILD_REPOSITORY}" \
    org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
    org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.revision=${BUILD_REF} \
    org.opencontainers.image.version=${BUILD_VERSION}
